CREATE TABLE movimento_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    valor_venda DECIMAL(19, 2),
    quantidade INTEGER NOT NULL,
    data_movimentacao TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);